"""Generate the English version under /en/."""
from html import escape
import json, shutil

OFFERS = {
 'weganskie-przepisy': ('Vegan recipes 400 kcal — e-book','More than 30 original vegan recipes of about 400 kcal per meal, with nutritional information.','More than 30 original vegan recipes. Each meal is approximately 400 kcal and includes protein, fat and carbohydrate information, plus practical preparation guidance.'),
 'dieta-spersonalizowany-plan-na-modelowanie-sylwetki-ebook-video': ('Personalised diet plan for body shaping','A one-month diet plan with more than 30 meals to choose from, matched to your goal.','A personalised one-month meal plan with more than 30 meals to choose from. The plan is adapted to your goal, calorie needs and preferred number of meals from one to six per day.'),
 'karta-prezentowa-weganski-trener': ('MikeMilekFitness gift card','A gift card for MikeMilekFitness products and services, available in several values.','A MikeMilekFitness gift card valid for six months. Choose the value that suits the person you want to support.'),
 'prowadzenie-przez-internet': ('Online coaching and consultations','Online coaching through WhatsApp with diet, training and progress monitoring, or a phone consultation.','Online coaching can include diet, training and progress monitoring. Phone consultations focus on plant-based nutrition and body shaping.'),
 'barki-autorskie-cwiczenia-ebook-video': ('Original exercises — e-book and video','Original gym exercises with descriptions, four photos and QR codes to video demonstrations.','A digital exercise guide with more than 100 pages per body part, four execution photos, descriptions and QR codes linking to video demonstrations.'),
 'trening-personalny-na-silowni': ('Personal training in Poznań','Personal gym training in Poznań: one hour or a package of five one-hour sessions.','Personal training at a gym in Poznań. The offer includes one-hour and five-session options, with variants for women and men.'),
 'trening-spersonalizowany-plan-modelowanie-sylwetki-ebook-video': ('Personalised monthly training plan','A monthly training plan matched to your goal, with exercise photos, descriptions and video QR codes.','A personalised monthly training plan. Strength exercises include four photos, professional descriptions and QR codes to video demonstrations.')
}

VARIANTS = {
 'Default Title':'E-book','Odchudzanie - Rzeźba - Redukcja  - Utrata Wagi':'Weight loss and definition',
 'Przybieranie Mięśni':'Muscle gain','Kobieta - 1h - Poznań':'Woman — 1 hour — Poznań',
 'Mężczyzna - 1h - Poznań':'Man — 1 hour — Poznań','Kobieta - 5x1h - Poznań':'Woman — 5 × 1 hour — Poznań',
 'Mężczyzna - 5x1h - Poznań':'Man — 5 × 1 hour — Poznań'
}

STATIC = {
 'aktualnosci.html':('News','No articles have been published yet.','<p>No articles have been published yet.</p>'),
 'partnerzy.html':('Partners','MikeMilekFitness partners.','<p><strong>Maczfit</strong> — vegan catering. The code “MieMił595” gives a 5% discount.</p><p><strong>Wypas</strong> — a fully vegan restaurant at Jackowskiego Street, Poznań.</p><p><strong>PoWolność</strong> — a restaurant at Kanałowa 15, Poznań.</p><p><strong>Szczaw i Mirabelki</strong> — a restaurant at Jaroczyńskiego 22, Poznań.</p>'),
 'warunki.html':('Terms of service','Terms of service for MikeMilekFitness.','<ol><li>MikeMilekFitness provides the services published on mikemilekfitness.com under these terms.</li><li>The services include individual and group training.</li><li>The provider may change and update services at any time without prior notice.</li><li>The provider may change these terms at any time without prior notice.</li><li>The provider undertakes to deliver services to the highest quality standards.</li><li>Services are provided on a payment-before-service basis.</li><li>The provider may cancel a service if payment is not received.</li><li>The provider undertakes to perform services reliably and diligently.</li><li>The provider is not liable for damage or loss caused by the services except where it results from intentional conduct or gross negligence.</li><li>The provider may refuse a service if it could harm the client’s health or if the client lacks sufficient ability to use the service safely.</li><li>Clients are responsible for personal belongings and clothing used during training.</li><li>The provider may refuse service when a client breaches these terms or has a negative impact on other clients.</li></ol>'),
 'zwroty.html':('Refund policy','Refund policy for MikeMilekFitness.','<ol><li>Products may be returned within 30 days from the date they are received by you or an authorised person.</li><li>Before returning a product, contact customer service at mieszkomilek@gmail.com and obtain approval.</li><li>Returned products must be unused, intact and packed according to the supplied instructions.</li><li>The full amount for an accepted return will be refunded within seven business days.</li><li>Digital products and services such as consultations and training are not refundable under the source policy. Contact us if you need assistance with a service.</li></ol>'),
 'wysylka.html':('Shipping and delivery','Shipping information for MikeMilekFitness.','<ol><li>MikeMilekFitness directs payments to PayPal.</li><li>Shipping is available in Poland and Europe. Customs duties and taxes may apply to international shipments.</li><li>Shipments are handled by a courier on business days and are not delivered on Saturdays or Sundays.</li><li>Shipping cost depends on product weight and type and the delivery address.</li><li>Orders placed before 11:00 local time are dispatched within 48 business hours.</li><li>Orders are delivered within seven business days from dispatch.</li><li>MikeMilekFitness is not responsible for delays caused by force majeure or unforeseen circumstances.</li><li>MikeMilekFitness is not responsible for courier damage or loss.</li></ol>'),
 'nota-prawna.html':('Legal notice','Legal notice for MikeMilekFitness.','<p>This website is owned and operated by MikeMilekFitness, based in Solec Kujawski, Poland. Contact: mieszkomilek@gmail.com.</p><ol><li>The website may be used only for lawful purposes.</li><li>Users are responsible for content they publish; MikeMilekFitness is not responsible for user-published content.</li><li>Personal data is processed under applicable data-protection law, including Regulation (EU) 2016/679 (GDPR).</li><li>Website text, images, audio, video, applications, logos and other materials belong to MikeMilekFitness or its licensors and may not be copied, distributed, published or used without written permission.</li><li>Details of personal-data processing are provided in the privacy policy.</li><li>The legal notice may be changed, modified or removed without prior notice.</li><li>Cookies may be used to adapt the website to user preferences; details are described in the privacy policy.</li><li>MikeMilekFitness is not responsible for damage or loss connected with use of the website.</li><li>This notice is governed by Polish law and disputes are decided by Polish common courts.</li></ol>'),
 'prywatnosc.html':('Privacy policy','Privacy information for MikeMilekFitness.','<h2>Contact and data</h2><p>Data provided in e-mail or WhatsApp correspondence is used to respond and handle agreed services.</p><h2>Using the website</h2><p>The website has no account registration, contact form or newsletter. It is hosted by GitHub Pages and embeds a YouTube video. These providers may receive technical connection data such as an IP address.</p><h2>External services</h2><p>E-mail, WhatsApp, PayPal, Instagram and Facebook operate under their providers’ terms. Contact us to request access, deletion or restriction of your data.</p>')
}

def head(title, description, url, pl_url):
 schema=json.dumps({'@context':'https://schema.org','@type':'WebPage','name':title+' | MikeMilekFitness','url':url,'inLanguage':'en'},ensure_ascii=False)
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(title)+' | MikeMilekFitness</title><meta name="description" content="'+escape(description)+'"><meta name="robots" content="index,follow"><link rel="canonical" href="'+url+'"><link rel="alternate" hreflang="pl" href="'+pl_url+'"><link rel="alternate" hreflang="en" href="'+url+'"><link rel="alternate" hreflang="x-default" href="https://mikemilekfitness.com/"><meta property="og:url" content="'+url+'"><meta property="og:title" content="'+escape(title)+' | MikeMilekFitness"><meta property="og:description" content="'+escape(description)+'"><meta property="og:type" content="website"><link rel="stylesheet" href="/styles.css?v=1.12"><link rel="stylesheet" href="/mobile-home.css?v=1.12"><link rel="stylesheet" href="/offer.css?v=1.12"><link rel="stylesheet" href="/social.css?v=1.12"><link rel="icon" href="/assets/favicon.svg"><script type="application/ld+json">'+schema+'</script><script src="/assets/js/language.js?v=1.12" defer></script></head>'

def header():
 return '<header class="header"><div class="header-inner"><a href="/en/" aria-label="MikeMilekFitness home"><img class="logo" src="/assets/shopify/files-black.png" width="50" height="60" alt="MikeMilekFitness logo"></a><span class="brand-wordmark">MikeMilek<span>Fitness</span></span><nav aria-label="Main navigation"><a href="/en/">Home</a><a href="/en/#oferta">Offers</a><a href="/en/kontakt.html">Contact</a><a href="/en/partnerzy.html">Partners</a></nav></div></header>'

def page(title, description, filename, body):
 url='https://mikemilekfitness.com/en/'+('' if filename=='index.html' else filename)
 pl='https://mikemilekfitness.com/'+('' if filename=='index.html' else filename)
 return head(title,description,url,pl)+'<body>'+header()+body+'<footer><div class="footer-bottom page-width"><span>© 2026 MikeMilekFitness</span><span>Version 1.12</span></div></footer></body></html>'

def price(product):
 return ('From ' if product['priceFrom'] else '')+f"{float(product['price']):.2f}".replace('.',',')+' PLN'

def card(product, config):
 title=OFFERS[product['handle']][0]
 return '<article class="product-card"><a class="product-image" href="'+product['handle']+'.html"><img src="/'+product['image']+'" width="600" height="600" loading="lazy" alt="'+escape(title)+'"></a><h3><a href="'+product['handle']+'.html">'+escape(title)+'</a></h3><p class="price">'+price(product)+'</p><a class="buy" data-sales-link href="'+config['paypalUrl']+'">Go to PayPal</a></article>'

def build(root, config, catalog):
 out=root/'_site'/'en'; out.mkdir(parents=True,exist_ok=True)
 cards=''.join(card(product,config) for product in catalog)
 home='<main id="main"><section class="hero"><img src="/assets/shopify/files-MIKE-3.jpg" width="4928" height="3264" alt="Mike Miłek during training" fetchpriority="high"><div class="hero-copy"><h1>MikeMilekFitness</h1><p>Training, mindful nutrition and getting in shape on your own terms.</p></div></section><section class="plant-story page-width"><div class="plant-story-inner"><p class="plant-kicker">The plant-based part of my story</p><h2>40 years old. Still in great shape.</h2><p>I have been vegetarian since 2017 and vegan since 2018. This is part of my life that I share alongside my training experience.</p></div></section><section class="intro page-width"><h2>My approach</h2><p>Hi, I am Mike. For more than 10 years I have shared my progress and supported clients online and in person.</p><p>I specialise in original plant-based diets and personalised training plans. Contact me to discuss your goal and my offer.</p></section><section id="oferta" class="offers page-width"><h2>MikeMilekFitness offers</h2><div class="product-grid">'+cards+'</div></section></main>'
 (out/'index.html').write_text(page('Training and mindful nutrition','Training, mindful nutrition, plant-based diets and personalised training plans.','index.html',home))
 (out/'oferta.html').write_text(page('Offers','Diet and training plans, e-books, consultations and personal training.','oferta.html','<main class="page-width simple-page"><h1>MikeMilekFitness offers</h1><div class="product-grid">'+cards+'</div></main>'))
 contact='<main class="page-width simple-page"><h1>Contact</h1><p>Contact me through WhatsApp or e-mail.</p><p><a class="buy" href="https://wa.me/48606708185">WhatsApp: +48 606 708 185</a></p><p><a class="buy" href="mailto:mieszkomilek@gmail.com">mieszkomilek@gmail.com</a></p><p><a href="https://instagram.com/weganskitrener">Instagram</a> · <a href="https://facebook.com/weganskitrener">Facebook</a></p></main>'
 (out/'kontakt.html').write_text(page('Contact','Contact MikeMilekFitness through WhatsApp, e-mail or social media.','kontakt.html',contact))
 for product in catalog:
  title,description,bodytext=OFFERS[product['handle']]
  variants=''.join('<tr><th scope="row">'+escape(VARIANTS.get(v['title'],v['title']))+'</th><td>'+str(v['price']).replace('.',',')+' PLN</td></tr>' for v in product['variants'])
  body='<main class="page-width simple-page offer-detail-page"><nav><a href="/en/">Home</a> · <a href="/en/oferta.html">All offers</a> · <a href="/en/kontakt.html">Contact</a></nav><h1>'+escape(title)+'</h1><img class="offer-cover" src="/'+product['image']+'" width="600" height="600" alt="'+escape(title)+'"><p>'+escape(bodytext)+'</p><table><caption>Options and prices</caption><tbody>'+variants+'</tbody></table><p><a class="buy" data-sales-link href="'+config['paypalUrl']+'">Go to PayPal</a></p></main>'
  (out/(product['handle']+'.html')).write_text(page(title,description,product['handle']+'.html',body))
 for filename,(title,description,content) in STATIC.items():
  (out/filename).write_text(page(title,description,filename,'<main class="page-width simple-page"><h1>'+title+'</h1>'+content+'</main>'))
 return [p.name for p in out.glob('*.html')]
